name: Check if web builds
on:
  pull_request:
    branches: [main]
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Format with Prettier
        run: npm run format
      - name: Lint with ESLint
        run: npm run lint
      - name: Build for web
        run: npm run web-build --if-present
